# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, users: List[int]=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param users: The users of this InlineResponse2002.  # noqa: E501
        :type users: List[int]
        """
        self.swagger_types = {
            'users': List[int]
        }

        self.attribute_map = {
            'users': 'users'
        }
        self._users = users

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def users(self) -> List[int]:
        """Gets the users of this InlineResponse2002.


        :return: The users of this InlineResponse2002.
        :rtype: List[int]
        """
        return self._users

    @users.setter
    def users(self, users: List[int]):
        """Sets the users of this InlineResponse2002.


        :param users: The users of this InlineResponse2002.
        :type users: List[int]
        """

        self._users = users
